-- 코드를 입력하세요
SELECT *

FROM (SELECT CAR_ID, A.CAR_TYPE, ROUND((DAILY_FEE * ((100-DISCOUNT_RATE)/100) * 30)) AS FEE
      FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
      ON A.CAR_TYPE = C.CAR_TYPE
      WHERE A.CAR_TYPE IN ("세단", "SUV")
      AND DURATION_TYPE LIKE "30%") D
      
WHERE FEE >= 500000 AND FEE < 2000000
AND CAR_ID NOT IN (SELECT B.CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
               WHERE START_DATE <= '2022-11-30'
               AND END_DATE >= '2022-11-01')
                 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC



# -- 대여 기록
#SELECT B.CAR_ID
#FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
#WHERE START_DATE <= '2022-11-01'
#AND END_DATE >= '2022-11-30';

-- 자동차 종류 별 대여 기간 종류 별 할인 정책 정보
# SELECT DISCOUNT_RATE
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
# WHERE (CAR_TYPE = "세댠" OR CAR_TYPE = "SUV")
# AND DURATION_TYPE LIKE "30%";