-- 코드를 입력하세요
SELECT R.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE) T
ON R.FOOD_TYPE = T.FOOD_TYPE
WHERE R.FAVORITES = T.MAX_FAVORITES
GROUP BY R.FOOD_TYPE
ORDER BY R.FOOD_TYPE DESC;

# SELECT FOOD_TYPE, MAX(FAVORITES)
# FROM REST_INFO
# GROUP BY FOOD_TYPE