-- 코드를 입력하세요
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR;

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM JULY
      GROUP BY FLAVOR) T
ON F.FLAVOR = T.FLAVOR
ORDER BY (F.TOTAL_ORDER + T.TOTAL_ORDER) DESC LIMIT 3;