-- 코드를 입력하세요
# SELECT CATEGORY, MAX(PRICE)
# FROM FOOD_PRODUCT
# GROUP BY CATEGORY
# HAVING CATEGORY IN ('과자', '국', '김치', '식용유')

SELECT P.CATEGORY, P.PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
      FROM FOOD_PRODUCT
      GROUP BY CATEGORY
      HAVING CATEGORY IN ('과자', '국', '김치', '식용유')) T
ON P.CATEGORY = T.CATEGORY
WHERE P.PRICE = T.MAX_PRICE
ORDER BY P.PRICE DESC;