-- 코드를 입력하세요
SELECT MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE

FROM MEMBER_PROFILE P LEFT OUTER JOIN REST_REVIEW R

ON P.MEMBER_ID = R.MEMBER_ID

WHERE P.MEMBER_ID IN (SELECT MEMBER_ID

FROM (SELECT MEMBER_ID, COUNT(*) CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID) C

      WHERE CNT = (SELECT MAX(CNT)
                   FROM (SELECT MEMBER_ID, COUNT(*) CNT
                         FROM REST_REVIEW
                         GROUP BY MEMBER_ID) C))
                         
ORDER BY REVIEW_DATE, REVIEW_TEXT