-- 코드를 입력하세요
WITH
TABLE_01 AS
(
SELECT B.AUTHOR_ID, B.CATEGORY, SUM(SALES) * PRICE AS TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES AS S
ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.BOOK_ID, B.AUTHOR_ID, B.CATEGORY
)

,

TABLE_02 AS
(
SELECT T1.AUTHOR_ID, A.AUTHOR_NAME, T1.CATEGORY, SUM(T1.TOTAL_SALES)
FROM TABLE_01 AS T1
JOIN AUTHOR AS A
ON T1.AUTHOR_ID = A.AUTHOR_ID
GROUP BY T1.AUTHOR_ID, T1.CATEGORY
)

SELECT *
FROM TABLE_02
ORDER BY AUTHOR_ID, CATEGORY DESC;