-- 코드를 입력하세요
# SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE LIKE '%Neutered%' OR SEX_UPON_INTAKE LIKE '%Spayed%', 'O', 'X') AS 중성화
# FROM ANIMAL_INS
# ORDER BY ANIMAL_ID;

-- 정규표현식 활용
SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE regexp 'Neutered|Spayed', 'O', 'X') AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;