-- 코드를 입력하세요
SELECT PRODUCT_ID, SUM(AMOUNT)
FROM FOOD_ORDER
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID;

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, T.TOTAL_AMOUNT * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE LIKE '2022-05%'
      GROUP BY PRODUCT_ID) T
ON P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;